package main

import (
	"log"

	"entgo.io/ent/entc"
	"entgo.io/ent/entc/gen"
	"github.com/inigolabs/entbrowse"
	"github.com/inigolabs/entbrowse/loader"
)

//go:generate go run gen.go

func main() {
	opts := []entc.Option{}

	err := entc.Generate("./schema", &gen.Config{
		Header: "// Code generated by entc, DO NOT EDIT.",
		Templates: []*gen.Template{
			entbrowse.Template(),
			loader.Template(),
		},
		Target:  "gen/ent",
		Package: "github.com/inigolabs/entbrowse/starwars/ent/gen/ent",
	}, opts...)
	if err != nil {
		log.Fatal("running ent codegen:", err)
	}
}
